export default {
  ON_GET_PARTICIPATES: "ON_GET_PARTICIPATES",
  ON_ADD_PARTICIPATE: "ON_ADD_PARTICIPATES",
  ON_DELETE_PARTICIPATE: "ON_DELETE_PARTICIPATES",
  ON_EDIT_PARTICIPATE: "ON_EDIT_PARTICIPATES",
};
